# Go application configuration file

# Database connection
[database]
username = "root"
password = "000000" # IMPORTANT: Use your actual password
dbname   = "system_info"

# domain_origin table data
# The domain name you want to accelerate and the corresponding IP
[[domain_origins]]
domain    = "example.com"
origin_ip = "192.168.1.100"

# node_region table data
# The server IP of deploying the forwarding 
[[node_regions]]
ip          = "172.16.0.10"
region      = "US-East"
hostname    = "node-use1-01.mydatacenter.com"
description = "Primary API server in US East"

[[node_regions]]
ip          = "172.16.1.20"
region      = "US-East"
hostname    = "node-euw2-db01.mydatacenter.com"
description = "Database replica in EU West"
