# Go application configuration file

# Database connection
[database]
username = "myapp_user"
password = "StrongAppUserPassword456!" 
dbname   = "myapp_db"

# domain_origin table data
# The domain name you want to accelerate and the corresponding IP
[[domain_origins]]
domain    = "example.com"
origin_ip = "192.168.1.100"

# node_region table data
# The server IP of deploying the forwarding 
[[node_regions]]
ip          = "172.16.0.10"
region      = "US-East"
hostname    = "node-use1-01.mydatacenter.com"
description = "US-East node 1"

[[node_regions]]
ip          = "172.16.1.20"
region      = "US-East"
hostname    = "node-use2-02.mydatacenter.com"
description = "US-East node 2"
