# Configuration file for the Go application

# Database connection details
[database]
username = "root"
password = "000000" # IMPORTANT: Change this to your actual password
dbname   = "system_info"

# Data to be inserted into domain_origin table
# This is an array of tables
[[domain_origins]]
domain    = "example.com"
origin_ip = "192.168.1.100"

# Data to be inserted into node_region table
# This is an array of tables
[[node_regions]]
ip          = "172.16.0.10"
region      = "US-East"
hostname    = "node-use1-01.mydatacenter.com"
description = "Primary API server in US East"

[[node_regions]]
ip          = "172.16.1.20"
region      = "US-East"
hostname    = "node-euw2-db01.mydatacenter.com"
description = "Database replica in EU West"

# Hostname and description are optional as per your table (can be NULL or empty)
# hostname    = ""
# description = ""