# traefik.yml

# --- Global Configuration ---
global:
  checkNewVersion: true
  sendAnonymousUsage: false # Set to true or false based on your preference

# --- Entry Points ---
entryPoints:
  web:
    address: ":80"
  # Define websecure here if your plugin or service requires HTTPS
  # websecure:
  #   address: ":443"

# --- API and Dashboard ---
api:
  insecure: true   # For testing only. Configure secure access in production.
  dashboard: true

# --- Logging ---
log:
  level: DEBUG     # Use DEBUG during testing for detailed information
  # filePath: "/var/log/traefik.log" # Optional: Specify log file path

# --- Certificate Resolvers ---
# Configure Let's Encrypt if needed
# certificatesResolvers:
#   myresolver:
#     acme:
#       email: "your-email@example.com"
#       storage: "acme.json"
#       httpChallenge:
#         entryPoint: "web"

# --- Providers ---
providers:
  # Remove or comment out the previous file provider if you used it to load domain-resolver.yml
  # file:
  #   directory: "/etc/traefik/conf.d" # Or your previous path
  #   watch: true

  # Add HTTP Provider pointing to your Go API server
  http:
    endpoint: "http://1.92.150.161:8090/traefik-dynamic-config" # <--- Modify this
    pollInterval: "10s"  # Frequency at which Traefik polls this endpoint, e.g., every 10 seconds
    # pollTimeout: "5s"    # Optional: Poll timeout

# --- Experimental Local Plugins ---
experimental:
  localPlugins:
    myWeightedRedirector: # Must match your plugin registration name
      moduleName: "weightedredirector" # Must match the module name and directory name in your plugin's go.mod